### ISSUE TITLE
upload demo mp4

### ISSUE THREAD

**Issue by SeeknnDestroy** [SeeknnDestroy/car-tracking-counting#4]
https://github.com/SeeknnDestroy/car-tracking-counting/assets/44926076/71c9dcb0-60ad-4cb7-99fe-509322bc2dde

**Comment by talhasarit** [comment]
![number_of_cars](https://github.com/SeeknnDestroy/car-tracking-counting/assets/44926076/a47785ab-36fe-4a33-836d-c0c8033d987b)

**Comment by talhasarit** [comment]
![total_count_of_cars](https://github.com/SeeknnDestroy/car-tracking-counting/assets/44926076/b55951c3-aa57-41a0-ba68-0ef4f0094d31)
